# Tensor

In Machine Learning, models are feed with a list of objects called feature vectors. A feature vector can be of any data type. The feature vector will usually be the primary input to populate a tensor. These values will flow into an op node through the tensor and the result of this operation/computation will create a new tensor which in turn will be used in a new operation. All these operations can be viewed in the graph.

<b>Note</b>: A tensor can be represented with a scalar or can have a shape of more than three dimensions. It is just more complicated to visualize higher dimension level.

# Properties of Tensor

A tensor is an object with three properties:
<ul>
    <li>A unique label (name)</li>
    <li>A dimension (shape)</li>
    <li>A data type (dtype)</li>
</ul>

# Types of Tensor

There are four main tensors you can create:
<ul>
    <li>tf.Variable</li>
    <li>tf.constant</li>
    <li>tf.placeholder</li>
    <li>tf.SparseTensor</li>
</ul>

# Representation of a Tensor

Tensors are represented as matrix of n-dimensions.<br>
A 3d matrix is represented like this -><br>
'''
[[[1,2,3]. <br>
   [4,5,6] <br>
   [7,8,9]]]

# Creating a Tensor

In [1]:
import tensorflow.compat.v1 as tf

In [3]:
constant1 = tf.constant(5, tf.int32)
print(constant1)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
constant2 = tf.constant(14, tf.int32, name = 'Constant_2')
print(constant2)

tf.Tensor(14, shape=(), dtype=int32)


In [7]:
constant3 = tf.constant([True, False, True], tf.int32, name = 'Constant_3')
print(constant3)
constant3.shape

tf.Tensor([1 0 1], shape=(3,), dtype=int32)


TensorShape([3])

# Useful Operators

<b>Note</b>: The output returned by these operators are actually a tensor object and not the result of the evaluation of the operation on the input tensors.
operatiors:
<ul>
    <li>tf.add(a, b)</li>
    <li>tf.substract(a, b)</li>
    <li>tf.multiply(a, b)</li>
    <li>tf.div(a, b)</li>
    <li>tf.pow(a, b)</li>
    <li>tf.exp(a)</li>
    <li>tf.sqrt(a)</li>
</ul>

In [10]:
# Add
tensor_a = tf.constant([[1,2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)

tensor_add = tf.add(tensor_a, tensor_b)
print(tensor_add)

# Multiply
tensor_multiply = tf.multiply(tensor_a, tensor_b)
print(tensor_multiply)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


# Variables

Data always arrive with different values, to capture this, you can use the Variable class. It will represent a node where the values always change. <br>

`tf.get_variable(name = "", values, dtype, initializer)`<br>
argument
- `name = ""`: Name of the variable
- `values`: Dimension of the tensor
- `dtype`: Type of data. Optional
- `initializer`: How to initialize the tensor. Optional
If initializer is specified, there is no need to include the `values` as the shape of `initializer` is used.<br>

<b>Note</b>:Here we dont use `tf.variable` to create a variable but use `tf.get_variable` unlike in case of constants we used tf.constant.

In [11]:
# creating a variable of 1 row and 2 cols
var = tf.get_variable("var", [1, 2])
print(var.shape)

(1, 2)


In [12]:
# using an initializer to initialize the variablesabs
var_init_1 = tf.get_variable("var_init_1", [1, 2], dtype=tf.int32,  initializer=tf.zeros_initializer)
print(var_init_1.shape)

(1, 2)


In [13]:
# we can also use a constant to initialize the variables
const1 = tf.constant([[10,20],[30,40]])
var_init_const1 = tf.get_variable("var_init_const1", dtype=tf.int32, initializer=const1)
print(var_init_const1)

<tf.Variable 'var_init_const1:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>


# Placeholders

A placeholder has the purpose of feeding the tensor. Placeholder is used to initialize the data to flow inside the tensors. To supply a placeholder, you need to use the method feed_dict. The placeholder will be fed only within a session.

The syntax is:

`tf.placeholder(dtype,shape=None,name=None )`<br>
arguments:
- `dtype`: Type of data
- `shape`: dimension of the placeholder. Optional. By default, shape of the data
- `name`: Name of the placeholder. Optional			
eg:
`data_placeholder_a = tf.placeholder(tf.float32, name = "data_placeholder_a")`

# Summary
<ol>
    <li><a href='#Tensor'>Definition of Tensor</a></li>
    <li><a href='#Properties-of-Tensor'>Properties of Tensor</a></li>
    <li><a href='#Types-of-Tensor'>Different types of Tensor Used</a></li>
    <li><a href='#Representation-of-Tensor'>Representation of Tensor</a></li>
    <li><a href='#Creating-a-Tensor'>How to create a Tensor</a></li>
    <li><a href='#Useful-Operations'>Useful operations on Tensors</a></li>
    <li><a href='#Variables'>Tensor Type: Variable</a></li>
    <li><a href='#Placeholder'>Tensor type: Placeholder</a></li>
</ol>